server:
  port: 8081

  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/xml, text/html, text/xml, text/plain

spring:
  application:
    name: Europeana Sitemap

management:
  endpoints:
    web:
      exposure:
        include: info, health

  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true