apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitemap-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: sitemap
          image: europeana/sitemap
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
            initialDelaySeconds: 110
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/readiness
            initialDelaySeconds: 110
            periodSeconds: 10
            failureThreshold: 6
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/opt/app/config/sitemap.user.properties"
          volumeMounts:
            - name: config
              mountPath: "/opt/app/config/sitemap.user.properties"
              readOnly: true
              subPath: sitemap.user.properties
      volumes:
        - name: config
          configMap:
            name: sitemap-config
